site_name: "C Programming Notes"
site_url: https://yxshkm404.github.io/c-programming-notes/
repo_url: https://github.com/yxshkm404/c-programming-notes
repo_name: GitHub

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Basics:
      - Data Types: Basics/Data Types.md
      - Program Structure: Basics/Program Structure.md
      - Input & Output: Basics/Input Output (printf, scanf).md
      - Control Flow: Basics/Control Flow (if-else).md
      - Loops: Basics/Loops.md
      - Functions: Basics/Functions.md
      - Pointers: Basics/Pointers.md
      - Memory Management: Basics/Memory Management.md
      - Strings: Basics/Strings.md
      - Structs & Unions: Basics/Structs & Unions.md
      - File I/O: Basics/File IO.md
      - Preprocessors & Macros: Basics/Preprocessors & Macros.md
      - Bitwise Operators: Basics/Bitwise Operators.md
  - Complexity Analysis:
      - Big O, Big Θ, Big Ω: Complexity Analysis/Big O, Big Θ, Big Ω.md
      - Time & Space Complexity: Complexity Analysis/Time & Space Complexity.md
  - Algorithms:
      - Sorting: Algorithms/Sorting.md
      - Searching: Algorithms/Searching.md
      - Recursion & Backtracking: Algorithms/Recursion & Backtracking.md
      - Dynamic Programming: Algorithms/Dynamic Programming.md
      - Greedy Algorithms: Algorithms/Greedy Algorithms.md
      - Graph Algorithms: Algorithms/Graph Algorithms.md
  - Data Structures:
      - Arrays: Data Structures/Arrays.md
      - Stack: Data Structures/Stack.md
      - Queue: Data Structures/Queue.md
      - Trees: Data Structures/Trees.md
      - Heap: Data Structures/Heap.md
      - Graphs: Data Structures/Graphs.md
      - Linked List: Data Structures/Linked List.md
      - Hashing: Data Structures/Hashing.md
      - Trie: Data Structures/Trie.md
  - Practice:
      - Easy: Practice/easy.md
      - Medium: Practice/medium.md
      - Hard: Practice/hard.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true